version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-nextjs
    container_name: portfolio-nextjs
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 